if: branch = master
language: objective-c
osx_image: xcode9.4
xcode_sdk: iphonesimulator
install:
  - CHANGES=$(git --no-pager diff --name-only $TRAVIS_COMMIT_RANGE)
  - if [[ -n "$(grep -Ei "(${PROJ_DIR}|\.travis\.yml)" <<< "$CHANGES")" ]]; then
      pod repo update;
    fi
script:
  - CHANGES=$(git --no-pager diff --name-only $TRAVIS_COMMIT_RANGE)
  - echo $CHANGES;
  - if [[ -n "$(grep -Ei "(${PROJ_DIR}|\.travis\.yml)" <<< "$CHANGES")" ]]; then
      pushd "$PROJ_DIR"; pod install; popd;
      xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO;
    fi
matrix:
  include:
  - name: "BannerTableViewExample"
    xcode_workspace: Swift/Advanced/BannerTableViewExample/BannerTableViewExample.xcworkspace
    env: PROJ_DIR="Swift/Advanced/BannerTableViewExample"
    xcode_scheme: BannerTableViewExample
  - name: "APIDemo"
    xcode_workspace: Swift/Advanced/APIDemo/APIDemo.xcworkspace
    xcode_scheme: APIDemo
    env: PROJ_DIR="Swift/Advanced/APIDemo"
  - name: "BannerExample"
    xcode_workspace: Swift/AdMob/BannerExample/BannerExample.xcworkspace
    xcode_scheme: BannerExample
    env: PROJ_DIR="Swift/AdMob/BannerExample"
  - name: "RewardedVideoExample"
    xcode_workspace: Swift/AdMob/RewardedVideoExample/RewardedVideoExample.xcworkspace
    xcode_scheme: RewardedVideoExample
    env: PROJ_DIR="Swift/AdMob/RewardedVideoExample"
  - name: "NativeAdvancedExample"
    xcode_workspace: Swift/AdMob/NativeAdvancedExample/NativeAdvancedExample.xcworkspace
    xcode_scheme: NativeAdvancedExample
    env: PROJ_DIR="Swift/AdMob/NativeAdvancedExample"
  - name: "InterstitialExample"
    xcode_workspace: Swift/AdMob/InterstitialExample/InterstitialExample.xcworkspace
    xcode_scheme: InterstitialExample
    env: PROJ_DIR="Swift/AdMob/InterstitialExample"
  - name: "AdManagerInterstitialExample"
    xcode_workspace: Swift/AdManager/AdManagerInterstitialExample/AdManagerInterstitialExample.xcworkspace
    xcode_scheme: AdManagerInterstitialExample
    env: PROJ_DIR="Swift/AdManager/AdManagerInterstitialExample"
  - name: "AdManagerBannerExample"
    xcode_workspace: Swift/AdManager/AdManagerBannerExample/AdManagerBannerExample.xcworkspace
    xcode_scheme: AdManagerBannerExample
    env: PROJ_DIR="Swift/AdManager/AdManagerBannerExample"
  - name: "AdManagerRewardedVideoExample"
    xcode_workspace: Swift/AdManager/AdManagerRewardedVideoExample/AdManagerRewardedVideoExample.xcworkspace
    xcode_scheme: AdManagerRewardedVideoExample
    env: PROJ_DIR="Swift/AdManager/AdManagerRewardedVideoExample"
  - name: "AdManagerCustomRenderingExample"
    xcode_workspace: Swift/AdManager/AdManagerCustomRenderingExample/AdManagerCustomRenderingExample.xcworkspace
    xcode_scheme: AdManagerCustomRenderingExample
    env: PROJ_DIR="Swift/AdManager/AdManagerCustomRenderingExample"
  - name: "BannerTableViewExample"
    xcode_workspace: Objective-C/Advanced/BannerTableViewExample/BannerTableViewExample.xcworkspace
    xcode_scheme: BannerTableViewExample
    env: PROJ_DIR="Objective-C/Advanced/BannerTableViewExample"
  - name: "APIDemo"
    xcode_workspace: Objective-C/Advanced/APIDemo/APIDemo.xcworkspace
    xcode_scheme: APIDemo
    env: PROJ_DIR="Objective-C/Advanced/APIDemo"
  - name: "BannerExample"
    xcode_workspace: Objective-C/AdMob/BannerExample/BannerExample.xcworkspace
    xcode_scheme: BannerExample
    env: PROJ_DIR="Objective-C/AdMob/BannerExample"
  - name: "RewardedVideoExample"
    xcode_workspace: Objective-C/AdMob/RewardedVideoExample/RewardedVideoExample.xcworkspace
    xcode_scheme: RewardedVideoExample
    env: PROJ_DIR="Objective-C/AdMob/RewardedVideoExample"
  - name: "NativeAdvancedExample"
    xcode_workspace: Objective-C/AdMob/NativeAdvancedExample/NativeAdvancedExample.xcworkspace
    xcode_scheme: NativeAdvancedExample
    env: PROJ_DIR="Objective-C/AdMob/NativeAdvancedExample"
  - name: "InterstitialExample"
    xcode_workspace: Objective-C/AdMob/InterstitialExample/InterstitialExample.xcworkspace
    xcode_scheme: InterstitialExample
    env: PROJ_DIR="Objective-C/AdMob/InterstitialExample"
  - name: "AdManagerInterstitialExample"
    xcode_workspace: Objective-C/AdManager/AdManagerInterstitialExample/AdManagerInterstitialExample.xcworkspace
    xcode_scheme: AdManagerInterstitialExample
    env: PROJ_DIR="Objective-C/AdManager/AdManagerInterstitialExample"
  - name: "AdManagerBannerExample"
    xcode_workspace: Objective-C/AdManager/AdManagerBannerExample/AdManagerBannerExample.xcworkspace
    xcode_scheme: AdManagerBannerExample
    env: PROJ_DIR="Objective-C/AdManager/AdManagerBannerExample"
  - name: "AdManagerRewardedVideoExample"
    xcode_workspace: Objective-C/AdManager/AdManagerRewardedVideoExample/AdManagerRewardedVideoExample.xcworkspace
    xcode_scheme: AdManagerRewardedVideoExample
    env: PROJ_DIR="Objective-C/AdManager/AdManagerRewardedVideoExample"
  - name: "AdManagerCustomRenderingExample"
    xcode_workspace: Objective-C/AdManager/AdManagerCustomRenderingExample/AdManagerCustomRenderingExample.xcworkspace
    xcode_scheme: AdManagerCustomRenderingExample
    env: PROJ_DIR="Objective-C/AdManager/AdManagerCustomRenderingExample"
